export const LOVE = 'LOVE';
export const HATE = 'HATE';
export const SELECT = 'SELECT';
export const DESELECT = 'DESELECT';
export const OUTCOME = 'OUTCOME'
export const HOME = 'HOME';

export const FETCH_HELLO_REQUEST = 'FETCH_HELLO_REQUEST';
export const FETCH_HELLO_RESPONSE = 'FETCH_HELLO_RESPONSE';
export const FETCH_GALLERY_REQUEST = 'FETCH_GALLERY_REQUEST';
export const FETCH_GALLERY_RESPONSE = 'FETCH_GALLERY_RESPONSE';
export const FETCH_GALLERY_FAILURE = 'FETCH_GALLERY_FAILURE';

